/**
 * Enable RN Fabric flag `useRawPropsJsiValue` so Vision Camera v5 can pass
 * Nitro HostObject props (e.g. PreviewView.previewOutput) through RawValue.
 *
 * RN 0.81.5 defaults this to false. It is a *native* flag — JS override APIs
 * cannot enable it. Requires a fresh native/EAS build (not OTA-only).
 */
const {
  createRunOncePlugin,
  withDangerousMod,
  withMainApplication,
  withAppDelegate,
  withXcodeProject,
  IOSConfig,
} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const TAG = 'withUseRawPropsJsiValue';

const ANDROID_IMPORT_FLAGS =
  'import com.facebook.react.internal.featureflags.ReactNativeFeatureFlags';
const ANDROID_IMPORT_CANARY =
  'import com.facebook.react.internal.featureflags.ReactNativeFeatureFlagsOverrides_RNOSS_Canary_Android';

const ANDROID_OVERRIDE = `
    // ${TAG}: Vision Camera PreviewView needs jsi::Value raw props (RN 0.81 default false).
    ReactNativeFeatureFlags.dangerouslyForceOverride(object : ReactNativeFeatureFlagsOverrides_RNOSS_Canary_Android() {
      override fun useRawPropsJsiValue(): Boolean = true
      override fun useShadowNodeStateOnClone(): Boolean = true
    })
`;

function withAndroidRawPropsFlag(config) {
  return withMainApplication(config, (cfg) => {
    let src = cfg.modResults.contents;
    if (src.includes('useRawPropsJsiValue(): Boolean = true')) {
      return cfg;
    }

    if (!src.includes(ANDROID_IMPORT_FLAGS)) {
      if (src.includes('import com.facebook.react.ReactNativeApplicationEntryPoint.loadReactNative')) {
        src = src.replace(
          'import com.facebook.react.ReactNativeApplicationEntryPoint.loadReactNative',
          `import com.facebook.react.ReactNativeApplicationEntryPoint.loadReactNative\n${ANDROID_IMPORT_FLAGS}\n${ANDROID_IMPORT_CANARY}`,
        );
      } else if (src.includes('import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.load')) {
        src = src.replace(
          'import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.load',
          `import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.load\n${ANDROID_IMPORT_FLAGS}\n${ANDROID_IMPORT_CANARY}`,
        );
      } else {
        throw new Error(
          `${TAG}: could not find MainApplication import anchor for React Native entry point`,
        );
      }
    }

    if (src.includes('loadReactNative(this)')) {
      src = src.replace(
        /loadReactNative\(this\)\s*\n/,
        `loadReactNative(this)\n${ANDROID_OVERRIDE}\n`,
      );
    } else if (/load\(\)\s*\n/.test(src)) {
      src = src.replace(/load\(\)\s*\n/, `load()\n${ANDROID_OVERRIDE}\n`);
    } else {
      throw new Error(`${TAG}: could not find loadReactNative(this) / load() in MainApplication`);
    }

    cfg.modResults.contents = src;
    return cfg;
  });
}

const IOS_H = `// Auto-generated by ${TAG}. Do not edit.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
void BWEnableUseRawPropsJsiValue(void);
#ifdef __cplusplus
}
#endif
`;

const IOS_MM = `// Auto-generated by ${TAG}. Do not edit.
#import "BWUseRawPropsJsiValue.h"

#include <react/featureflags/ReactNativeFeatureFlags.h>
#include <react/featureflags/ReactNativeFeatureFlagsOverridesOSSStable.h>

namespace {
class UseRawPropsJsiValueProvider final
    : public facebook::react::ReactNativeFeatureFlagsOverridesOSSStable {
 public:
  bool useRawPropsJsiValue() override { return true; }
};
} // namespace

void BWEnableUseRawPropsJsiValue(void) {
  // Prefer force-override so caches from Stable bootstrap are discarded.
  facebook::react::ReactNativeFeatureFlags::dangerouslyForceOverride(
      std::make_unique<UseRawPropsJsiValueProvider>());
}
`;

function ensureIosNativeFiles(projectRoot, projectName) {
  const destDir = path.join(projectRoot, projectName);
  if (!fs.existsSync(destDir)) return null;
  const hPath = path.join(destDir, 'BWUseRawPropsJsiValue.h');
  const mmPath = path.join(destDir, 'BWUseRawPropsJsiValue.mm');
  fs.writeFileSync(hPath, IOS_H);
  fs.writeFileSync(mmPath, IOS_MM);
  return { hPath, mmPath, destDir };
}

function withIosNativeSources(config) {
  config = withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const projectName = IOSConfig.XcodeUtils.getProjectName(cfg.modRequest.projectRoot);
      ensureIosNativeFiles(cfg.modRequest.platformProjectRoot, projectName);
      return cfg;
    },
  ]);

  config = withXcodeProject(config, (cfg) => {
    const projectName = IOSConfig.XcodeUtils.getProjectName(cfg.modRequest.projectRoot);
    const project = cfg.modResults;
    const file = `${projectName}/BWUseRawPropsJsiValue.mm`;
    if (!project.hasFile(file)) {
      project.addSourceFile(file, { target: project.getFirstTarget().uuid });
    }
    return cfg;
  });

  config = withAppDelegate(config, (cfg) => {
    let src = cfg.modResults.contents;
    if (src.includes('BWEnableUseRawPropsJsiValue')) {
      return cfg;
    }

    const isSwift = cfg.modResults.language === 'swift' || src.includes('import Expo');

    if (isSwift) {
      if (!src.includes('BWUseRawPropsJsiValue')) {
        // Bridging via module map is awkward in CNG; call through a tiny ObjC
        // wrapper exposed with @_silgen_name after ensuring the .mm is linked.
        src = src.replace(
          /import ReactAppDependencyProvider\n/,
          `import ReactAppDependencyProvider\n\n@_silgen_name("BWEnableUseRawPropsJsiValue")\nfunc BWEnableUseRawPropsJsiValue()\n`,
        );
      }
      if (src.includes('return super.application(application, didFinishLaunchingWithOptions: launchOptions)')) {
        src = src.replace(
          'return super.application(application, didFinishLaunchingWithOptions: launchOptions)',
          `let bwLaunchOk = super.application(application, didFinishLaunchingWithOptions: launchOptions)
    // After RN Stable feature-flag bootstrap so Vision Camera PreviewView gets jsi raw props.
    BWEnableUseRawPropsJsiValue()
    return bwLaunchOk`,
        );
      } else if (src.includes('return super.application(')) {
        src = src.replace(
          /return super\.application\(([\s\S]*?)\)\n/,
          `let bwLaunchOk = super.application($1)\n    BWEnableUseRawPropsJsiValue()\n    return bwLaunchOk\n`,
        );
      }
    } else {
      // ObjC AppDelegate
      if (!src.includes('BWUseRawPropsJsiValue.h')) {
        src = src.replace(
          /#import "AppDelegate.h"/,
          `#import "AppDelegate.h"\n#import "BWUseRawPropsJsiValue.h"`,
        );
      }
      src = src.replace(
        /didFinishLaunchingWithOptions:[\s\S]*?\{/,
        (m) => `${m}\n  BWEnableUseRawPropsJsiValue();`,
      );
    }

    cfg.modResults.contents = src;
    return cfg;
  });

  return config;
}

const withUseRawPropsJsiValue = createRunOncePlugin(
  (config) => {
    config = withAndroidRawPropsFlag(config);
    config = withIosNativeSources(config);
    return config;
  },
  'withUseRawPropsJsiValue',
  '1.0.0',
);

module.exports = withUseRawPropsJsiValue;
